---
- name: Collecte des infos système via AD
  hosts: all
  gather_facts: false
  become: true
  vars:
    ansible_user: "{{ ad_user }}"
    ansible_password: "{{ ad_password }}"
    ansible_connection: winrm
    ansible_winrm_transport: kerberos
    ansible_winrm_server_cert_validation: ignore

  tasks:
    - name: Collecter les faits système
      setup:

    - name: Afficher la RAM
      debug:
        msg: "RAM totale : {{ ansible_memory_mb.real.total }} MB"

    - name: Afficher les infos CPU
      debug:
        msg: "CPU(s) : {{ ansible_processor_count }} - Modèle : {{ ansible_processor[1] }}"

    - name: Afficher les infos disque
      debug:
        msg: >
          Disques :
          {% for disk in ansible_devices %}
            {{ disk }} - Taille : {{ ansible_devices[disk].size }}
          {% endfor %}
