---
- name: Récupérer la version de l'OS
  hosts: all
  gather_facts: yes
  become: false

  tasks:
    - name: Afficher la distribution
      debug:
        msg: "Distribution : {{ ansible_distribution }}"

    - name: Afficher la version de la distribution
      debug:
        msg: "Version : {{ ansible_distribution_version }}"

    - name: Afficher la version majeure
      debug:
        msg: "Version majeure : {{ ansible_distribution_major_version }}"
