#---
# Metadata
#version: "0.0.1"
#author: "Michael D <dtmghislain@gmail.com>"
#comment: "Part of ansible_labs project named nix_sysadmin for automating linux administration tasks"
#repos_dev: "https://github.com/michaeldefo/ansible_labs/tree/feature/install_node_exporter - branch for DEV"
#repos_main: "https://github.com/michaeldefo/ansible_labs.git to commit on global repos"

- name: Create node_exporter user
  user:
    name: "{{ node_exporter_user }}"
    shell: /usr/sbin/nologin
    system: yes
    create_home: no

- name: Download Node Exporter binary
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter.tar.gz"

- name: Extract Node Exporter
  unarchive:
    src: "/tmp/node_exporter.tar.gz"
    dest: "/opt/"
    remote_src: yes

- name: Move binary to /usr/local/bin
  copy:
    src: "/opt/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    remote_src: yes
    mode: '0755'

- name: Create systemd service
  copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Prometheus Node Exporter
      After=network.target

      [Service]
      User={{ node_exporter_user }}
      ExecStart=/usr/local/bin/node_exporter --web.listen-address=:{{ node_exporter_port }}
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd and start node_exporter
  systemd:
    daemon_reload: yes
    name: node_exporter
    enabled: yes
    state: started

# Uncomment if using firewalld on CentOS
# - name: Open firewall port
#   firewalld:
#     port: "{{ node_exporter_port }}/tcp"
#     permanent: yes
#     state: enabled
#     immediate: yes
#   when: ansible_facts['distribution'] == "CentOS"
