- name: Download Harbor installer
  get_url:
    url: https://github.com/goharbor/harbor/releases/download/v2.9.0/harbor-online-installer-{{ habor_version }}.tgz ### version harbor v2.9.0
    dest: /opt/harbor.tgz

- name: Extract Harbor
  unarchive:
    src: /opt/harbor.tgz
    dest: /opt/
    remote_src: yes

- name: Create Harbor user
  user:
    name: "{{ harbor_usr }}"
    shell: /usr/sbin/nologin
    home: "{{ harbor_home }}"
    create_home: yes
    system: yes

- name: Set ownership of Harbor data
  file:
    path: "{{ harbor_home }}"
    owner: "{{ harbor_usr }}"
    group: "{{ harbor_usr }}"
    recurse: yes

- name: Configure harbor.yml
  template:
    src: harbor.yml.j2
    dest: "{{ harbor_usr }}/harbor.yml"

- name: Install Harbor
  command: ./install.sh chdir={{ harbor_usr }}
